name: Build and Release Vencord-Scheduled

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Standalone
        run: pnpm build --standalone 

      - name: Generate plugin list
        run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

      - name: Zip Build
        run: zip -r Vencord-Scheduled-Edition.zip dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Vencord-Scheduled-Edition.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
